#ifndef OPERATIONS_GLOBAL_H
#define OPERATIONS_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef OPERATIONS_LIB
# define OPERATIONS_EXPORT Q_DECL_EXPORT
#else
# define OPERATIONS_EXPORT Q_DECL_IMPORT
#endif

#endif // OPERATIONS_GLOBAL_H
