#ifndef FEATUREEXTRACTION_GLOBAL_H
#define FEATUREEXTRACTION_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef FEATUREEXTRACTION_LIB
# define FEATUREEXTRACTION_EXPORT Q_DECL_EXPORT
#else
# define FEATUREEXTRACTION_EXPORT Q_DECL_IMPORT
#endif

#endif // FEATUREEXTRACTION_GLOBAL_H
