#pragma once

enum PortDataType
{
	DATATYPE_INT,
	DATATYPE_MATRIX,
	DATATYPE_HISTOGRAM,
	DATATYPE_GRAYIMAGE,
	DATATYPE_8UC3IMAGE,
	DATATYPE_BINARYIMAGE,
	END_DATATYPE_MATRIX,

	DATATYPE_STRING,
	DATATYPE_USERTYPE,
	DATATYPE_INVALID,
};