#ifndef DESIGNNETPROJECTEXPLORER_GLOBAL_H
#define DESIGNNETPROJECTEXPLORER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef DESIGNNETPROJECTEXPLORER_LIB
# define DESIGNNETPROJECTEXPLORER_EXPORT Q_DECL_EXPORT
#else
# define DESIGNNETPROJECTEXPLORER_EXPORT Q_DECL_IMPORT
#endif

#endif // DESIGNNETPROJECTEXPLORER_GLOBAL_H
