#ifndef FLOWERFEATUREEXTRACTION_GLOBAL_H
#define FLOWERFEATUREEXTRACTION_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef FLOWERFEATUREEXTRACTION_LIB
# define FLOWERFEATUREEXTRACTION_EXPORT Q_DECL_EXPORT
#else
# define FLOWERFEATUREEXTRACTION_EXPORT Q_DECL_IMPORT
#endif

#endif // FLOWERFEATUREEXTRACTION_GLOBAL_H
